### ISSUE TITLE
Maximum Callstack exceeded with gzip compressed WebGL build

### ISSUE THREAD

**Issue by zmays** [game-ci/unity-builder#225] opened 2021-03-02 15:00 UTC
**Bug description**

I'm using a custom docker image with the most recent editor release:

```
FROM unityci/editor:ubuntu-2020.1.13f1-webgl-0.10.0

RUN apt-get update && apt-get install ffmpeg -y
```

I was using 0.9.0, upgraded to 0.10.0, changed player settings to use gzip, and was able to successfully build, but when trying to load project in chrome, am getting this console error after everything loads:

<img width="1932" alt="Screen Shot 2021-03-02 at 8 55 20 AM" src="https://user-images.githubusercontent.com/4370615/109667125-7157e180-7b35-11eb-8718-9d671456bc10.png">

**How to reproduce**

I know you have a test project, and that probably built, but did you test opening in the browser? If so this is probably just an issue with my own project, but I figured I'd just get this on your radar

**Expected behavior**

No callstack error

**Comment by zmays** [comment] 2021-03-02 16:28
I built again after changing some settings and it seems to be working now

**Comment by webbertakken** [comment] 2021-03-02 16:38
Do you have a diff of which settings you changed?

It might be very helpful.

**Comment by zmays** [comment] 2021-03-02 16:58
Yeah here is the diff (sorry for the screenshot):

<img width="1224" alt="Screen Shot 2021-03-02 at 10 54 19 AM" src="https://user-images.githubusercontent.com/4370615/109684392-d582a180-7b45-11eb-8d5b-17f55370bcea.png">


beats me why linear intensity and active color space would matter, I was changing those tangentially, perhaps the automatic webgl support setting, but I'm not sure why that would be the case. Nothing else changed between the build that didn't work and the new one with these changes. I was manually setting content-encoding gzip on the build assets, but I don't think I messed that up

**Comment by davidmfinol** [comment] 2021-03-15 02:17
Closing the issue as it seems to be resolved. Please re-open if it reappears, or send a comment if you get more clarity on root cause.

**Closed by davidmfinol** 2021-03-15 02:17 UTC
Labels: bug
