### ISSUE TITLE
WEBGL Build is corrupted

### ISSUE THREAD

**Issue by Ben-v-starloop** [game-ci/unity-builder#306] opened 2021-12-20 22:38 UTC
**Bug description**

I followed your github actions video on youtube. The webgl builds are corrupted
check here : https://ben-v-starloop.github.io/GameCI/
I get unityFramewok is not defined
**How to reproduce**
follow the tutorial, make webgl build via the trigger, try to open the game and get the error.
Compressing is disabled on local project. maybe requires some remote settings?

![image](https://user-images.githubusercontent.com/93995909/146842032-34459468-fbaa-460d-926f-8bbb14a906ca.png)

**Comment by webbertakken** [comment] 2021-12-20 23:05
Hi @Ben-v-starloop, thank you for your bug report.

Would you mind adding sufficient details to actually reproduce the issue?

Thank you.

**Comment by Ben-v-starloop** [comment] 2021-12-21 19:30
You can simply have a look at the repo that is public! You can even
download it ! Is just an empty scene with a cube. I pushed to the GitHub
repository, I created a worklow named main.yml which is the exact copy of
the template.yml you mention in the video, I run it and deploys the game to
github pages on the separate branch gh-pages.
The build as you see in the link is broken, it hangs, to throwing the error
unityframework not defined.

Il Mar 21 Dic 2021, 00:06 Webber Takken ***@***.***> ha
scritto:

**Comment by webbertakken** [comment] 2021-12-21 20:44
> The build as you see in the link is broken

I'm trying to help by narrowing down the cause to something specific so that we can start thinking about how to solve the issue.

> follow the tutorial, make webgl build via the trigger

There is a reason we provide issue templates. 

A link to the repository (not the deployment) along with information about the unity version and any settings you may have changed may help speed up the process.

**Comment by Ben-v-starloop** [comment] 2021-12-22 09:33
Dear Webber,

As you can see from my account I have only this repository, that is the
one, where you can find the code and the template as well.
https://github.com/Ben-v-starloop/GameCI/

I wrote you all the steps, nothing more. I did not anything special 😃

Thank you,
Best regards,
Ben


Il Mar 21 Dic 2021, 21:44 Webber Takken ***@***.***> ha
scritto:

**Comment by Ben-v-starloop** [comment] 2021-12-22 09:34
And Yes I used unity 2020.3.20

Il Mar 21 Dic 2021, 21:44 Webber Takken ***@***.***> ha
scritto:

**Comment by webbertakken** [comment] 2022-05-22 11:38
Closing this for the lack of steps to reproduce.

**Closed by webbertakken** 2022-05-22 11:38 UTC
Labels: bug, need steps to reproduce
