### ISSUE TITLE
MacOS build fails with unity-builder but not with unity-test-runner ? 

### ISSUE THREAD

**Issue by achimmihca** [game-ci/unity-builder#295] opened 2021-10-28 20:32 UTC
**Bug description**

- my StandaloneLinux64 build fails with GitHub Actions
- It does not fail on my local machine
- Other targetPlatforms also do not fail with GitHub Actions, although there is no platform specific code.
- Running same project with unity-test-runner for StandaloneLinux64 also does not fail. But a true compiler error should fail the build (I think ?)
- Log says "Error building Player because scripts had compiler errors", but it does not tell me, in which file the the compiler error occurs.
- Log says a lot "/bin/sh: 1: mktemp: not found", maybe this is related?

**How to reproduce**

- Happens when I run the unity-builder on https://github.com/UltraStar-Deluxe/Play/actions
- Please find the configuration here: https://github.com/UltraStar-Deluxe/Play/blob/master/.github/workflows/build-unity-project.yml
    - As I said, this unity-test-runner works: https://github.com/UltraStar-Deluxe/Play/blob/master/.github/workflows/test-unity-project.yml

**Expected behavior**

The build should be consistent with the unity-test-runner build - and should not fail.

I don't know how I should debug this issue.
Is there a parameter I can set to get more log output from unity-builder?

**Comment by achimmihca** [comment] 2021-10-29 20:45
I upgraded the project to Unity 2021.2.0f1.

The good news is that the Linux build is working now.
The bad news is that now the MacOS build is failing.
It is similar to before, but now with mac. However, there are different log outputs of course.

Anyway, 
- The MacOS build works with the unity-test-runner.
    - https://github.com/UltraStar-Deluxe/Play/actions/runs/1400508769 
- The MacOS build works on my local machine (building on Windows for MacOS).

I am again bit lost on this, because I am not a MacOS user.
Please, find the log here: https://github.com/UltraStar-Deluxe/Play/runs/4050822575?check_suite_focus=true

Any ideas?

**Comment by achimmihca** [comment] 2021-10-30 15:23
I am also unable to build my minimal test project: https://github.com/achimmihca/UnityTestProject
I removed the space in the project's name to see if this is causing the issue. But the build still fails.
However, the build on my local machine works fine (for macOS as well as iOS)

Maybe its an issue with the new Unity 2021.2 version?
I think the output location of Unity's build artifact is slightly different than in 2021.1

**Comment by davidmfinol** [comment] 2021-10-30 23:24
Could it be some issue related to Burst? I see these in your logs:
https://github.com/achimmihca/UnityTestProject/runs/4055552669?check_suite_focus=true#step:7:2472
https://github.com/achimmihca/UnityTestProject/runs/4055552640?check_suite_focus=true#step:7:3068

I'd recommend using Linux laptop (or VM) to try building your project.

**Comment by MaxwellDexter** [comment] 2021-11-09 23:44
Also getting issues building for macOS on 2021.2. No issues for Linux and Windows builds.
We're using Burst 1.6.1.
[macos_build_on_ubuntu_errors.txt](https://github.com/game-ci/unity-builder/files/7508673/macos_build_on_ubuntu_errors.txt)
Here are some errors, not sure if they're the cause though. I couldn't find much else in the logs that was concerning though.

**Comment by davidmfinol** [comment] 2021-11-10 00:31
@MaxwellDexter 
Have you tried using your personal Linux laptop or VM to build the macOS version?
I think that would be the first place to start debugging this error.

**Comment by davidmfinol** [comment] 2022-02-28 02:16
Looks like this issue is actually a duplicate of https://github.com/game-ci/unity-builder/issues/320, which should be fixed soon by https://github.com/game-ci/docker/pull/158

**Closed** 2022-04-02 16:01 UTC
Labels: bug, duplicate
