### ISSUE TITLE
il2cpp build stuck both on IOS and Android

### ISSUE THREAD

**Issue by zivbaz** [game-ci/unity-builder#344] opened 2022-02-23 12:54 UTC
We're using GitHub action to build our apps, using a self-hosted ubuntu instance.
Building both IOS and Android.
When building with 2019.4.35f1 Unity version, the build process is done successfully.
We needed to upgrade the Unity version to 2020.3.27f1.
The build process is done successfully with the new version when building the apps on our private laptops (Mac).
But when we try to build with the new version on GitHub action, the build process is stuck when reaching the il2cpp part.
We can see that il2cpp execution was changed on the 2020 Unity version.

2019.4.35f1 log output:
`Invoking il2cpp with arguments: --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARM64" --configuration="Release" --outputpath="/github/workspace/Solitaire/Temp/StagingArea/assets/bin/Data/Native/arm64-v8a/libil2cpp.so" --cachedirectory="/github/workspace/Solitaire/Assets/../Library/il2cpp_android_arm64-v8a/il2cpp_cache" --additional-include-directories="/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/Tools/bdwgc/include" --additional-include-directories="/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/Tools/libil2cpp/include" --tool-chain-path="/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/NDK" --map-file-parser="/opt/unity/Editor/Data/Tools/MapFileParser/MapFileParser" --generatedcppdir="/github/workspace/Solitaire/Temp/StagingArea/Il2Cpp/il2cppOutput" --dotnetprofile="unityaot" 
2022-02-22T14:49:42.5297118Z /opt/unity/Editor/Data/il2cpp/build/deploy/net471/il2cpp.exe exited after 46124 ms.`

2020.3.27f1 log output:
`Invoking il2cpp (via bee.exe) with arguments: --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARMv7" --configuration="Release" --outputpath="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/Native/armeabi-v7a/libil2cpp.so" --cachedirectory="/github/workspace/Solitaire/Assets/../Library/il2cpp_android_armeabi-v7a/il2cpp_cache" --additional-include-directories="/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/Tools/bdwgc/include" --additional-include-directories="/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/Tools/libil2cpp/include" --baselib-directory="/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/Variations/il2cpp/Release/StaticLibs/armeabi-v7a" --avoid-dynamic-library-copy --tool-chain-path="/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/NDK" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/AppsFlyeriOSWrapper.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/BraintreeViewController.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/NSInvocation+Convenience.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/Reachability.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/RiskifiedBeacon.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/SkAdNetworkManager.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/TrackingAuthorizationManager.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/UASupportPrimitivesBox.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/UASupportTools.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/UnityAdsInitializationListener.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/UnityAdsLoadListener.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/UnityAdsShowListener.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/UnityAppController+Notifications.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/UnityNotificationManager.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/UnityNotificationWrapper.h" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/externs.cpp" --additional-cpp="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/additionalCppFiles/iOSBridge.h" --profiler-report --map-file-parser="/opt/unity/Editor/Data/Tools/MapFileParser/MapFileParser" --directory="/github/workspace/Solitaire/Temp/StagingArea/assets/bin/Data/Managed" --generatedcppdir="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/il2cppOutput" --stats-output-dir="/github/workspace/Solitaire/Library/Il2cppBuildCache/Android/armeabi-v7a/il2cppStats"`

Some Tecnical details:

`Unity Editor version:    2020.3.27f1 (e759542391ea)
Branch:                  2020.3/release
Build type:              Release
Batch mode:              YES
System name:             Linux
Distro version:          #31~20.04.1-Ubuntu SMP Fri Jan 14 14:37:50 UTC 2022
Kernel version:          5.11.0-1028-aws
Architecture:            x86_64
Available memory:        189124 MB`

`Unity Editor version:    2019.4.35f1 (0462406dff2e)
Branch:                  2019.4/staging
Build type:              Debug
Batch mode:              YES
System name:             Linux
Distro version:          #31~20.04.1-Ubuntu SMP Fri Jan 14 14:37:50 UTC 2022
Kernel version:          5.11.0-1028-aws
Architecture:            x86_64
Available memory:  189124 MB`

**Comment by zivbaz** [comment] 2022-02-24 13:58
I add a thread I opened in the Unity forum - https://forum.unity.com/threads/il2cpp-build-stuck-both-on-ios-and-android.1244608/

**Comment by webbertakken** [comment] 2022-02-26 13:34
If it is indeed the IL2CPP process as indicated by Unity staff, you might try patching it's binaries using a private image.

**Comment by zivbaz** [comment] 2022-02-28 14:55
@webbertakken thank you.
What do you mean by "patching its binaries"?
Can you please elaborate on it?

**Comment by webbertakken** [comment] 2022-02-28 16:35
I just mean replacing the IL2CPP binary with a different version and publishing an image with that change, then try if it works.

To be honest I'm not so sure if it's indeed related to a binary. Looks like a project specific setting or something. The issue is from 2014 and there are no additional answers or solutions to the problem; which there would be if it was a widespread problem.

**Comment by AndrewKahr** [comment] 2023-12-14 05:10
Closing as these versions are EOL

**Closed by AndrewKahr** 2023-12-14 05:10 UTC
Labels: bug, bug in unity
