### ISSUE TITLE
Unity builds for StandaloneOSX are not runnable.

### ISSUE THREAD

**Issue by dyarosla** [game-ci/unity-builder#77] opened 2020-03-14 17:21 UTC
When building for **StandaloneOSX**, the resultant file uploaded to artifacts isn't runnable.

If you add executable permissions to the artifact the project can then be run.

```bash
chmod +x [PATH-TO-ARTIFACT]/StandaloneOSX/StandaloneOSX.app/Contents/MacOS/*
```

I'm not entirely sure where this would be added in the build pipeline, but I imagine these permissions should be added prior to artifact upload.

**Comment by webbertakken** [comment] 2020-03-14 17:53
Hi @dyarosla, 

Thanks for reporting this. 

I guess this should be run after the creation of the build, at the end of `build.sh`, only for OSX Standalone and Linux Standalone builds, as the Windows Standalone build seems to be fine.

Feel free to draft a pull request!

**Comment by dyarosla** [comment] 2020-03-14 19:16
Yeah that would be a good spot for it as the build target is all set up there already. That said, don't know how you'd prefer to separate compile-target specific code.

**Comment by webbertakken** [comment] 2020-03-14 19:32
You will have to use BUILD_TARGET variable which is passed in [here](https://github.com/webbertakken/unity-builder/blob/master/src/model/docker.js#L43) and match it for one of the platforms in the [platform](https://github.com/webbertakken/unity-builder/blob/master/src/model/platform.js) model class

**Comment by mastef** [comment] 2020-10-06 10:42
So not sure if there's a regression happening, but it was not runnable for me with a recent build ( `LSOpenURLsWithRole() failed with error -10810 for the file /Downloads/Build/StandaloneOSX/StandaloneOSX.app.`

I needed to `chmod +x` everything manually for now. I documented that regression in the PR https://github.com/webbertakken/unity-builder/pull/99#issuecomment-704184130

**Comment by GabLeRoux** [comment] 2020-10-08 19:53
I did reproduce the issue where StandaloneOSX's executable needs to be chmod +x for the app to start. I wonder what's going on. Tested with recent 2020.1.7f1 version on a very simple project here:
https://github.com/Unity-CI/unity-actions-example

**Comment by GabLeRoux** [comment] 2020-10-08 20:20
I tried again with `-nographics` and `@master` (which uses `unitybuilder@v1.4` right now) and I also reproduced `LSOpenURLsWithRole() failed with error -10810 for the file /Downloads/Build/StandaloneOSX/StandaloneOSX.app.` here: https://github.com/Unity-CI/unity-actions-example/tree/9f0672b9e4a79c738bcf2814c6a893cd66e196d5.

@webbertakken there seem to be a regression. I'll spin a matrix with all `unity-builder` and try to locate the regression

**Comment by aidan-waite** [comment] 2020-10-19 14:29
Incase it's useful, I ran into this issue today and doing `chmod +x StandaloneOSX.app/Contents/MacOS/*` in terminal allows me to open the app

**Comment by webbertakken** [comment] 2020-11-09 19:27
There was a commit reverted that should solve this problem. 

Please confirm.

**Comment by jsm174** [comment] 2020-12-02 16:26
Should this be fixed in `webbertakken/unity-builder@v2.0-aplha-5`?  

I am seeing this issue as well.

**Comment by webbertakken** [comment] 2020-12-02 18:08
Yea it should have been, but perhaps there's still something wrong.

We had reverted some user permissions as far as I remember, but yea I also think we should give the executable bit to the file prior to uploading if it doesn't already.

Accepting PRs for this.

**Comment by Zetonia** [comment] 2021-03-07 13:15
Is this still an issue, since updating I am seeing our app is damaged. Tried the above solutions but they do not work.
![Screenshot 2021-03-07 at 13 14 57](https://user-images.githubusercontent.com/80185221/110241148-37c51300-7f47-11eb-8aef-ef8ad55517ca.png)

**Comment by webbertakken** [comment] 2021-03-07 19:23
If you use the default build path it [should work](https://github.com/game-ci/unity-builder/blob/0934b3f408f01aa0d4902476af40d955c43c11bf/action/steps/build.sh#L143).

If it doesn't we'd appreciate any help to debug the issue.

**Comment by mastef** [comment] 2021-03-08 00:56
I'm running this command before creating the dmg : 

```
      - name: Restore executable permissions
        run: |
          find StandaloneOSX -type f -iname "MapFileParser" -exec chmod +x {} \;
          find StandaloneOSX -type f -iname "*.sh" -exec chmod +x {} \;
          find StandaloneOSX -type f -iname "usymtool" -exec chmod +x {} \;
          find StandaloneOSX -type f -iname "lzma" -exec chmod +x {} \;
```

**Comment by Zetonia** [comment] 2021-03-11 21:39
None of the above worked for me however I did notice with the downloaded application that it has extra attributes when running 
```
ls -la
drwxr-xr-x@ 3 <Zetonia>  staff    96 11 Mar 01:26 zetonia.app
	com.apple.quarantine	  57 
```

If i run the following command on the file then it opens fine.

```
xattr -d com.apple.quarantine zetonia.app
```

**Comment by webbertakken** [comment] 2021-03-11 22:20
Should we be removing the extended attributes? What's your view on this?

**Comment by Zetonia** [comment] 2021-03-14 03:31
OK - I managed to pull the docker images locally and build my project (rather than on gitlab ci) and they have no issue. 
Doing some reading it looks like when apps are zipped then the latest release of MacOS has an issue and quarantines them [reference1](https://forum.unity.com/threads/osx-code-signing.455830/)., [reference2](https://forum.unity.com/threads/the-application-cannot-be-opened.404388/).

Looks like we can get around this by Notarizing the builds [reference](https://gist.github.com/dpid/270bdb6c1011fe07211edf431b2d0fe4).

**Comment by davidmfinol** [comment] 2021-03-14 07:56
It sounds like distributing a macOS app pretty much now requires going through the `codesign` process. I believe the initial issue  (builds not runnable without `chmod +x path/to/executable`) has been fixed, so maybe we should close this issue and open a new issue for documentation about macOS distribution? We may want to create a `docs/github/deployment/macos` page that goes into `codesign`, notarization, and maybe even fastlane for mac apps.

**Comment by webbertakken** [comment] 2021-03-14 10:39
Feel free to reopen for issues related to not being runnable.

**Closed** 2021-03-14 10:38 UTC
Labels: enhancement, good first issue

**Comment by Zetonia** [comment] 2021-03-14 12:41
For reference found this issue on the unity tracker -> https://issuetracker.unity3d.com/issues/macos-builds-now-contain-a-quarantine-attribute and also a mention of it being fixed in https://unity3d.com/unity/beta/2021.1.0b8

**Comment by jamescrowley** [comment] 2024-01-24 22:12
I just encountered this for the first time building our app on MacOS. The command that worked for me, mentioned here https://issuetracker.unity3d.com/issues/macos-builds-now-contain-a-quarantine-attribute was running both these commands:

```
xattr -rc XXXX.app
chmod +x XXXX.app/Contents/MacOS/*
```
 
 Anyone have an idea why this would still be an issue?

**Comment by jamescrowley** [comment] 2024-01-24 22:16
If anyone finds this on Google like I did, there's a more up to date issue discussing this here: https://github.com/game-ci/documentation/issues/262
