### ISSUE TITLE
Unity Pro license ? Build issue

### ISSUE THREAD

**Issue by YannGROS** [game-ci/unity-builder#288] opened 2021-09-06 15:18 UTC
Hey guys ! 
I'm new to CI/CD, and I was trying to figure out how to set up all of this with Unity.

Here's my yml file :
```yaml
name: Build Unity Project

on: [push, pull_request, workflow_dispatch]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - NameOfMyProjectFolderWhereMyUnityProjectIs
        unityVersion:
          - 2019.4.5f1
        targetPlatform:
          - StandaloneWindows64 # Build a Windows64 standalone.
          - WebGL # WebGL.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Cache
        uses: actions/cache@v2
        with:  
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          
      - name: Upload          
        uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
          path: build/${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
```

My unity project is in a subfolder, this is why I've got a projectPath.

I always have an issue at the build step and I can't get rid of it.

I tried several things :
- changing unity password to avoid special characters
- Unity - Activate (I read somewhere that with the pro version it's not necessary)
- using the UNITY_LICENSE like personnal license

Nothing is working, I think some help would be useful !

(The log for the above : [logs_15.zip](https://github.com/game-ci/unity-builder/files/7116788/logs_15.zip), and I also had the "License activation strategy could not be determined.")

**Comment by davidmfinol** [comment] 2021-09-06 18:46
I see this in your logs: 
```
An error occurred while resolving packages:
2021-09-06T15:03:05.4279424Z   Project has invalid dependencies:
2021-09-06T15:03:05.4281097Z     com.picarros.serializabledictionary: The file [/github/workspace/SITE/Packages/E:/Users/yann.gros/Desktop/GitHub/SerializableDictionary/package.json] cannot be found
2021-09-06T15:03:05.4282286Z 
2021-09-06T15:03:05.4283781Z A re-import of the project may be required to fix the issue or a manual modification of /github/workspace/SITE/Packages/manifest.json file
```

The problem is that you have some dependencies in your manifest.json incorrectly configured. To fix, I'd recommend cloning the repo on a new computer, and trying to build it on that other computer.

**Comment by YannGROS** [comment] 2021-09-07 13:05
Thank you @davidmfinol , it seems it was the problem !

I've got a "No files were found with the provided path" issue with actions/upload-artifact@v2 now...

**Comment by davidmfinol** [comment] 2021-09-07 15:03
I think you want this:
```yaml
path: build/${{ matrix.targetPlatform }}
```

**Comment by YannGROS** [comment] 2021-09-07 15:11
Why would it work with this pattern and not the other ? What does this part change ?
```yaml
-${{ matrix.unityVersion }}
```
Isn't it just the name of a folder ? There's definitely something I'm missing.

Thank you for the help !

**Comment by webbertakken** [comment] 2021-09-07 15:48
The path is the name of the folder indeed. It does not include unity version.
For the name you can put whatever you like.

**Comment by davidmfinol** [comment] 2021-09-09 23:01
@YannGROS It sounds like you've got it working now, right? Good to close this issue?

**Closed** 2021-09-10 08:04 UTC
