### ISSUE TITLE
versioning 'Tag' causes an error on build.gradle

### ISSUE THREAD

**Issue by estellise-yukihime** [game-ci/unity-builder#286] opened 2021-09-04 15:13 UTC
**Bug description**

```
Warning: Could not parse "1.0.5
" to semver, defaulting android version code to 1
```

```
FAILURE: Build failed with an exception.

* Where:
Build file '/github/workspace/Temp/gradleOut/launcher/build.gradle' line: 26

* What went wrong:
Could not compile build file '/github/workspace/Temp/gradleOut/launcher/build.gradle'.
> startup failed:
  build file '/github/workspace/Temp/gradleOut/launcher/build.gradle': 26: expecting ''', found '\n' @ line 26, column 27.
             versionName '1.0.5
                               ^
  
  1 error
```

**Additional details**

[Sample Project](https://github.com/estellise-a/sample-tag)

Tested only on unity versions

- 2019.4.12f1
- 2020.3.10f1

**Comment by webbertakken** [comment] 2021-09-04 16:41
Thank you for reporting this bug.

It might be related to a missing trim here https://github.com/game-ci/unity-builder/blob/3ebdb0e6788e6b438396b6eb37b348d88db2a2f4/src/model/versioning.ts#L267

**Comment by RaadDalaq** [comment] 2021-09-04 23:04
> Thank you for reporting this bug.
> 
> It might be related to a missing trim here
> 
> https://github.com/game-ci/unity-builder/blob/3ebdb0e6788e6b438396b6eb37b348d88db2a2f4/src/model/versioning.ts#L268

Yep, we fixed it on our side by just trimming the version before assigning it in unity.

**Comment by webbertakken** [comment] 2021-09-05 00:15
@RaadDalaq would you be willing to create a PR for that?

**Comment by RaadDalaq** [comment] 2021-09-05 02:22
@webbertakken It was through our unity C# build pipeline, not sure if it's applicable, we didn't modify the repo, I can try and fix it in my fork later, just a bit busy currently.

**Comment by estellise-yukihime** [comment] 2021-09-05 08:55
> Thank you for reporting this bug.
> 
> It might be related to a missing trim here
> 
> https://github.com/game-ci/unity-builder/blob/3ebdb0e6788e6b438396b6eb37b348d88db2a2f4/src/model/versioning.ts#L268

I see, thank you, for now, I just tried to trim on `versioning.ts` it, and currently just works perfectly on my end.

**Comment by webbertakken** [comment] 2021-09-05 09:27
Great @estellise-yukihime. would you be willing to create a PR for that?

**Comment by estellise-yukihime** [comment] 2021-09-06 05:35
> Great @estellise-yukihime. would you be willing to create a PR for that?

I can, but this is only a 1 line fix and this is my 1st time doing typescript I don't know if what I did is the correct way.

**Comment by estellise-yukihime** [comment] 2021-09-06 05:41
@webbertakken, This is the [PR - 287](https://github.com/game-ci/unity-builder/pull/287).

**Comment by webbertakken** [comment] 2021-09-06 16:36
Fixed by https://github.com/game-ci/unity-builder/pull/287 in https://github.com/game-ci/unity-builder/releases/tag/v2.0-alpha-13. 

Please feel free to comment if the issue is in fact not resolved.

**Closed by webbertakken** 2021-09-06 16:36 UTC
Labels: bug
