### ISSUE TITLE
Permission error GitHub self hosted

### ISSUE THREAD

**Issue by antoiner77** [game-ci/unity-builder#598] opened 2023-11-16 12:02 UTC
**Bug description**
Hey, not sure this is for you of for GitHub, but since I upgraded from V2 to V4 I got this error and my GitHub worker won't even start: 

`Error: One or more errors occurred. (Access to the path '/home/ubuntu/actions-runner/_work/_actions/game-ci/unity-builder/v4/dist/BlankProject/Logs/Packages-Update.log' is denied.) (Access to the path '/home/ubuntu/actions-runner/_work/_actions/game-ci/unity-builder/v4/dist/BlankProject/Library/AnnotationManager' is denied.)`

the file are created as root, and so after one run everything is stuck as the worker can't access root owned files

-

**Additional details**

On self-hosted GitHub worker, ubuntu

**Comment by AndrewKahr** [comment] 2023-11-16 14:16
Whoops, didn't check on self hosted. Can you test to see if `game-ci/unity-builder@perm-fix` fixes the issue? If it does we can get that merged to main and release a hot fix for v4.

**Comment by antoiner77** [comment] 2023-11-16 14:23
Starting a build :)

**Comment by antoiner77** [comment] 2023-11-16 14:43
@AndrewKahr I can confirm that the fix is working on self-hosted worker

**Comment by AndrewKahr** [comment] 2023-11-16 15:39
Should be merged and released on v4. Thanks for reporting and testing the fix!

**Comment by antoiner77** [comment] 2023-11-16 15:40
Thanks for the quick fix !

**Closed by AndrewKahr** 2023-11-16 15:39 UTC
Labels: bug

**Comment by DenverGylee** [comment] 2024-01-02 03:57
I came across this issue as I was recently dealing with it using `ubuntu-2022.3.16f1-windows-mono-3`. I am manually running `sudo chmod -R 777 BlankProject` when this image is used for the first time. Is there a way I can check that https://github.com/game-ci/unity-builder/pull/599 is indeed included in the image?

Here are more details on the image I am using
```
REPOSITORY       TAG                                 IMAGE ID       CREATED        SIZE
unityci/editor   ubuntu-2022.3.16f1-windows-mono-3   e4524a860edd   4 days ago     7.72GB
```

**Comment by webbertakken** [comment] 2024-01-02 09:55
The change isn't in the image, it's in builder. It has since be release albeit not mentioned with the issue number in the release notes.

**Comment by irinkovCas** [comment] 2024-01-03 15:47
The issues seems to persist on releases 4.1.1 and up as the fix `chmod -R 777 "/BlankProject"` has been removed. Here is a link to the removed line: https://github.com/game-ci/unity-builder/commit/8ca1282c9eabf4b053576f63611d21ee855b80db#diff-7281a8eb0d31d7677d0cb266f17ec342d462f1bd4baba01764925f35b1f5c9d6L24

I'm not sure if just bringing it back would fix the issue.

**Comment by Epicguru** [comment] 2024-04-09 22:40
This issue seems to still be happening even though it is marked as fixed.
I am using the latest version of the builder and tester, `unity-test-runner` version v4.1.1 and `unity-builder` v4.2.3,
on a self-hosted Ubuntu runner.

The issue is exactly the same as described here, works fine the first time, subsequent runs fail to start due not being able to access the path.
Using `checkout@v4.1.1` in case that matters.

I've seen issues suggesting that this is actually a Github actions-related issue, if that is the case is there any known workaround?
I do not want to run my build pipeline as root for fairly obvious security reasons.

Thanks.

**Comment by Epicguru** [comment] 2024-04-09 22:47
Ignore my comment: I found the documentations for the `runAsHostUser` option, which does exactly what I want and solves this issue. I'll leave my comment for other people who find this issue through Google.

https://game.ci/docs/github/test-runner#runashostuser

**Comment by mfbrantner** [comment] 2025-03-12 09:46
@lisa-arvis Try `rm -rf`-ing the `_work` directory on your runner.
It might still contain some files owned by `root`.
