### ISSUE TITLE
Build fails because of empty scene

### ISSUE THREAD

**Issue by firatkucuk** [game-ci/unity-builder#302] opened 2021-12-04 22:21 UTC
**Bug description**

Build fails because of empty initial scene value:

this is my `EditorBuildSettings.asset` file:

```yaml
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!1045 &1
EditorBuildSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_Scenes:
  - enabled: 1
    path: Assets/Levels/Level1.unity
    guid: 2cda990e2423bbf4892e6590ba056729
  m_configObjects: {}
```

but in `Builder.cs` following line retuns an array of empty string `['']`

```csharp
var scenes = EditorBuildSettings.scenes.Where(scene => scene.enabled).Select(s => s.path).ToArray();
```

I tried to print the exact values:

```csharp
foreach (var xscene in EditorBuildSettings.scenes) {
  System.Console.WriteLine(xscene.enabled);
  System.Console.WriteLine(xscene.path);
}
```

The result is:

```
True

```

**How to reproduce**

Create a project with `2021.2.3f1` version and use and try to run github actions with default values.

**Expected behavior**

A Passing pipeline, I injected manually and it passes

```csharp
var scenes = new[] { "Assets/Levels/Level1.unity" };
```

**Comment by webbertakken** [comment] 2021-12-04 23:02
You should have one of your scenes selected from the editor. 
Builder does not choose which scenes to build by itself.

Just to confirm, the `EditorBuildSettings.asset` that you're showing, is it committed in that state?

**Comment by webbertakken** [comment] 2021-12-04 23:38
Possibly related to https://github.com/game-ci/unity-builder/issues/113?

**Comment by sqddnt** [comment] 2021-12-05 08:07
i have the same problem with 2021.2.3f1, just followed the instructions, nothing specific

**Comment by firatkucuk** [comment] 2021-12-05 08:52
You can check the following pipeline and project content:

https://github.com/firatkucuk/super-firro/runs/4421395911?check_suite_focus=true

**Comment by davidmfinol** [comment] 2021-12-05 09:01
I'm not certain, but I suspect the problem is related to the missing .meta files. 
Any reason you're not using .meta files in git?

**Comment by firatkucuk** [comment] 2021-12-05 09:45
gitignore.io generates gitignore files without meta extension when you select `Unity`

**Comment by firatkucuk** [comment] 2021-12-05 10:01
@davidmfinol seems you're right. pipeline passed with metafiles, thanks.

But those files seemed redundant to me like mac `.DS_Store` files, when you start unity it automatically creates all of them.

So can we put a mechanism into the builder itself either checking meta files existence or automatically create them?

**Comment by webbertakken** [comment] 2021-12-05 10:43
If it were always possible to auto generate them, there would be no point to having these `.meta` files in the first place.

The meta files store settings and `guids` about those files, which ensure correct behaviour of your project. So they are indeed required. 

A mechanism to go against Unity specs does not seem to be the right solution.

Was the problem solved for you by adding the meta files?

**Comment by firatkucuk** [comment] 2021-12-05 11:16
Yes it's solved, Gonna create a PR for gitignore.io, and If you want I can create a PR for checking meta-file existence to the unity builder? Apart from that mystery is solved. thanks guys.

**Closed** 2021-12-05 11:29 UTC
Labels: bug

**Comment by webbertakken** [comment] 2021-12-05 11:30
Feel free to create another ticket about your ideas for this meta-file check. It might be useful.
